# Generated by Django 2.2.19 on 2022-09-04 14:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220902_1628'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipe_ingredient_exists',
        ),
        migrations.RemoveConstraint(
            model_name='shoppinglist',
            name='shopping_recipe_user_exists',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Задайте время приготовления блюда', validators=[django.core.validators.MinValueValidator(1, message='время должно быть больше нуля.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_recipe', to='recipes.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Придумайте уникальный URL адрес', unique=True, verbose_name='Адрес'),
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='un_favorite'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipe_ingredient_ex'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='shopping_recipe_user'),
        ),
    ]
